### ISSUE TITLE
Multiple Inconsistently-Appearing Errors in ZNode List

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#10]
- Some nodes which have been down for a long time are marked as ENABLED.

- Some nodes have duplicate rankings.

- Some nodes have negative ranking.

**Comment by riordant** [comment]
Looks like this is definitely still an issue. It appears to be client related as I can see that the publisher is pushing all data related to Znodes

**Comment by riordant** [comment]
Looks like this is definitely still an issue, on both ends

**Comment by justanwar** [comment]
This is an ongoing problem with the znode list. @psolstice could shed more light on it.

**Comment by riordant** [comment]
We will relook at this once the Znode refactor is complete

**Comment by sproxet** [comment]
b643c14bc refactored the Zcoin list, but as the issues were inconsistent, I can't confirm whether or not that solved them. If anyone still experiences the issue running the latest master (which will soon be packaged to v0.0.2), please comment here again.

**Comment by riordant** [comment]
I think this should remain open until the Znode refactor (on the daemon side). The issues with the rank (at least) are related to that. We can keep this issue as a reference point until then.

**Comment by riordant** [comment]
Given the recent overhaul of the Znode page, I think this can be closed. All data present now is consistently correct. By the time we add non-wallet Znodes, the Znode module in the daemon will have been refactored.
