### ISSUE TITLE
zcoind fails to respect -dandelion=0

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#132]
If Zcoin Client is configured to use regtest, it will pass `-dandelion=0` when starting zcoind (as can be confirmed in `ps`), however zcoind will ignore this (as can be confirmed in `await $daemon.getSettings()`).

**Comment by riordant** [comment]
Fixed in https://github.com/zcoinofficial/zcoin/commit/877488a6c4f7e2c80835c51e72e11ab2721db814
