### ISSUE TITLE
Shutdown Sometimes Hangs on OS X

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#17]
It looks like in these cases, zcoind does shut down successfully.

**Comment by riordant** [comment]
I have reproduced this bug recently, unfortunately it does not seem to be consistent

**Comment by riordant** [comment]
@sproxet Bump - Recent report of this again from @catchingknives. `zcoind` has shutdown, what's left in Activity Monitor is:
```
Zcoin Client
Zcoin Client Helper
Zcoin Client Helper
```

**Comment by riordant** [comment]
There is a good chance that this will be fixed by the process management code refactor. As a result we will move this to 1.0 milestone.

**Comment by sproxet** [comment]
Unfortunately, the workaround for this had to be reverted in 547c9677783 due to issues with shutdown, and the problem has reappeared. I believe this is related to the libzmq issue https://github.com/zeromq/cppzmq/issues/139 and that we'll have to fix it there. Luckily this only occurs on OS X.
