### ISSUE TITLE
Better Detection of Daemon Errors

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#21]
Currently the UI does not recognise when the daemon is in Safe Mode, and still allows normal interaction. This needs to be exposed by the 0MQ API and then rendered as completely blocking in the client. (It's not helpful for the client to have any functionality in this case; displayed data will be incorrect.)

**Comment by sproxet** [comment]
We should probably try to detect any other anomalous conditions as well.

**Comment by riordant** [comment]
Blocking added in Safe Mode. the api status method is the only method still allowed; a `safeMode` key has been added here also. If other anomalous conditions come up we can handle them as they come.
