### ISSUE TITLE
Restart Daemon Screen Hangs On Daemon Crashes During Bootup

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#24]

**Comment by riordant** [comment]
@sproxet can you provide more details? I presume you mean the `Connect to other nodes via Tor` option?

**Comment by sproxet** [comment]
@riordant This issue is related to the client failing to handle a daemon crash if it occurs during startup. The specific zcoind crash that was causing me issues here was already fixed, but the issue that the client can't gracefully handle a zcoind segfault during that period (as it can during others) remains.

**Comment by qashban4** [comment]
related to #51  #52

**Comment by riordant** [comment]
@sproxet is this still an issue?
