### ISSUE TITLE
Client Hangs on Boot if Reindex is Required

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#29]
If a reindex is required on starting zcoind, zcoind will shut down and the client won't notice this, hanging forever. We should probably change the behaviour to automatically reindex while displaying a notification to the user about the issue.

**Comment by riordant** [comment]
Fix added in https://github.com/zcoinofficial/zcoin/commit/4dab95d7d3665029d10be4a7ec55d4fd859f75b0. The solution is to force reindex if this situation occurs.
