### ISSUE TITLE
Reindex is slower than on regular zcoind

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin-client#31]
## Actual behaviour

Reindex is significantly slower than on regular Zcoind

## Desired behaviour
Should match regular Zcoind reindex.

**Comment by riordant** [comment]
https://github.com/zcoinofficial/zcoin-client/issues/37 related

**Comment by riordant** [comment]
This is solved in https://github.com/zcoinofficial/zcoin/commit/bca2279fdaabf6b333e44ed20f97a2d1e5ecea9d. Excessive logging is removed, which brings sync to within 5% sync time of bare `zcoind` on master.
