### ISSUE TITLE
GUI wallet is not aware when reindex is required when replacing wallet.dat

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin-client#32]
## Actual behaviour
Wallet shows as synced even when replacing wallet.dat

## Desired behaviour
Should prompt for reindex where required.

## Steps to reproduce
Wait till current wallet is synced.
Close wallet.
Replace wallet.dat with another wallet.dat 
Open up GUI.

**Comment by riordant** [comment]
I have confirmed that Qt also does not prompt for reindex. What is the particular error that you are experiencing?
