### ISSUE TITLE
Initializing Blockchain text....

### ISSUE THREAD

**Issue by vampyren** [zcoinofficial/zcoin-client#40]
Hi,

I'm guessing this is placeholder text but i will send it in anyway just in case. 
During my first startup i got this:
https://1drv.ms/u/s!Ag9C_L5-r1CxhPN7VewzgNA2-R7lcA?e=8Vq9Wm

Is this a bug or will the funny text be replaced?

**Comment by riordant** [comment]
You are correct, it is placeholder text.

**Comment by vampyren** [comment]
Ok then my bad sorry.

**Comment by riordant** [comment]
Sorry, let me clarify - it is placeholder text and it needs to be removed. For reference, this is the text:
```
Adipiscing Tristique Ullamcorper Ornare Consectetur
```
