### ISSUE TITLE
Zcoin Client Creates Multiple Data Directories

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#41]
The client uses multiple directories, and this might be confusing to users. It might be better if all data was stored in the same directory that vanilla zcoind uses.

**Comment by sproxet** [comment]
Unfortunately, it seems like we don't actually know where the zcoind data dir is going to be until we either boot up zcoind or read it from our cache. I suppose the easiest thing to do is to replicate the default datadir location as defined in zcoind and then place our config information there, but that seems like it might also be very confusing if we've set zcoind to exist in a non-default location (in which case the Zcoin Client config file would still be in the default zcoind data directory).

I'm removing this from the 0.0.3 board as it's quite a minor thing from the user perspective and the optimal behaviour really isn't immediately clear to me. I'll have a think on it and revisit the issue later.

**Comment by qashban4** [comment]
Need lot of testing on different OS. @sproxet to get VMware working asap
