### ISSUE TITLE
Stuck on Loading blockchain

### ISSUE THREAD

**Issue by hakonamatata** [zcoinofficial/zcoin-client#44]
Hi

I had the old zcoin client running, then I opened the new zcoin client v.0.0.2 at the same time. This caused the new zcoin client to get stuck in the "loading blockchain" state. Restarting the zcoin client without the old one running worked fine.

**Comment by sproxet** [comment]
I'm closing this since it is a case of #24, as zcoind itself can't be run concurrently, and thus crashes on startup. Hopefully the situation there will be improved soon. Thanks for testing. :)
