### ISSUE TITLE
zcoin shows wrong total when minting

### ISSUE THREAD

**Issue by hakonamatata** [zcoinofficial/zcoin-client#45]
I had 5 Zcoin. Doing two 1 zcoin mints. 

So it should say 3 + (2 pending), but it says 3 + (4 pending)? 

![image](https://user-images.githubusercontent.com/4003969/64076800-be9d8d80-ccc9-11e9-9aab-ddbfbb74f84d.png)

**Comment by hakonamatata** [comment]
Follow up, after the minting got one confirmation, it shows the correct amount. 3 + (2 pending).

**Comment by hakonamatata** [comment]
After 17 confirmation, it still says pending and I can not do private send. When I close the app and open it again, it says that I have 2 zcoin available for private send, but it shows a suggestion for anonymizing coins, when I just did and 50% of my zcoins are already minted.

**Comment by sproxet** [comment]
@hakonamatata I just opened an issue regarding the part about being unable to do private sends. The suggestion for anonymizing Zcoins may or may not be related to the current issue (#45), so I'm not opening a third issue for it. If issues occur related to the suggestion erroneously appearing again after 0.0.3 drops, please report it separately.

**Comment by hakonamatata** [comment]
![image](https://user-images.githubusercontent.com/4003969/64082737-16f97d00-cd14-11e9-8a0a-ce827aa6b0df.png)
Another example, one mint, shows up as two pending.

**Comment by sproxet** [comment]
This should be fixed by zcoinofficial/zcoin@96bfacf448c5.
