### ISSUE TITLE
"Connection to the Zcoin Deamon lost" message following initial wallet lock

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#51]
On Mac OSX. Daemon is still running in the background. Clicking "restart" does not fix the issue, however after restarting the client, operation continues normally.

**Comment by justanwar** [comment]
Can confirm, facing this issue on 0.0.4 Windows 10 after initial wallet lock.

**Comment by riordant** [comment]
Solved as of 0.0.5.
