### ISSUE TITLE
User Should Be Notified When Transactions Are Orphaned

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#62]
Currently when a transaction is orphaned, the existing transaction is just left in the list until the client restarts. zcoind needs to be modified so that it emits events in this situation, and then zcoin-client should remove the transaction from the list or mark it somehow as orphaned and untrustworthy.

**Comment by riordant** [comment]
Thinking about solutions to this: I could add the `stateWallet` call as a publisher method, and under any circumstance that it occurs, the client will clear it's tx list and repopulate with it's contents. Then in the daemon when reorg is detected, it's triggers this event. How does that sound

**Comment by sproxet** [comment]
Somewhere along the line the behaviour has changed to correctly marking orphaned transactions as unconfirmed. Closing.
