### ISSUE TITLE
Password requirements should be reconsidered

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#63]
Qt and `zcoind` have little requirements on the strength of the password. Now passwords have much stronger requirements from the client and are mandatory. To discuss on the path to take for this.

**Comment by hakonamatata** [comment]
I would just like to comment that many more people have lost their crypto by forgetting their password, then actually getting hacked. So, I would suggest not having too hard requirements here.

**Comment by catchingknives** [comment]
I agree. If users are educated on the consequences, they should be able to make their own decision in regard to the password strength. 

What I'm not sure about is whether it should be possible to run off of an unencrypted wallet file. That would be a very easy target for a simple trojan.

**Comment by justanwar** [comment]
I'm for mandatory passwords, but a total no to password strength requirement.
