### ISSUE TITLE
Mint data should be shown at the "Receive" page

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#64]
Currently this is all that's shown:
<img width="426" alt="Screenshot 2019-09-26 at 17 19 19" src="https://user-images.githubusercontent.com/6988731/65680816-ef32d600-e081-11e9-8412-3bb014da5acb.png">

To show `Transaction ID:` As the other transactions do.

**Comment by sproxet** [comment]
This was added yesterday in 7f98219.
