### ISSUE TITLE
Metadata About Payment Requests Remains After Deleting wallet.dat

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#7]
This completely breaks the consistency of data displayed.

**Comment by riordant** [comment]
@sproxet the `persistent` contains all the new data that `zcoind` needs to work with the client. What metadata are you referring to?

**Comment by sproxet** [comment]
@riordant This was referencing data the client was keeping around related to Payment Request seen state. After the refactor, the client no longer keeps this information.
