### ISSUE TITLE
"Last page" button in Znode list goes to empty page

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#74]
![Screenshot 2019-10-04 at 00 13 14](https://user-images.githubusercontent.com/6988731/66148825-fe92c000-e63b-11e9-95e6-396fc873c172.png)
![Screenshot 2019-10-04 at 00 13 33](https://user-images.githubusercontent.com/6988731/66148831-005c8380-e63c-11e9-807c-8a633b9164d9.png)

Clicking the button on the far right on the first image above goes to an empty page, with no possibility to get back to the Znode page with navigating away from it. It seems to reset to the original page once a new Znode update comes in.

**Comment by sproxet** [comment]
Remote Znode list is being removed.
