### ISSUE TITLE
Remove the znode list for those not owned by wallet owner

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#76]
After discussion with @reubenyap , we think it's better to remove the Znode List that does not involve the wallet. General users have no use for this list and if so, can access it via RPC calls.
Steps:
- Daemon: remove znodeList publishing, remove non-wallet Znodes from `znodeList` function
- Client: Remove `znodeList` subscriber

**Comment by riordant** [comment]
Daemon fix added in https://github.com/zcoinofficial/zcoin/commit/75efffb078096e132bcfe8517fc61af243153ec9

**Comment by sproxet** [comment]
This is implemented in 65c7423 and d95191f.
