### ISSUE TITLE
"In x minutes" should say "In roughly x minutes" during transaction sync, time varies significantly between blocks

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#87]
Otherwise it may confuse the user into thinking it's an exact amount when in reality it's a (very rough) estimation. Once it passes it's estimation on the final block, it begins to say "x minutes ago", which doesn't make sense.
Also on the daemon side: to review why `avgBlockTime` varies so signficantly between blocks (This is the value that's used to estimate the time until sync).

**Comment by reubenyap** [comment]
Maybe just put the In ~x minutes.

**Comment by justanwar** [comment]
For "Average Days for Payout", we can go with this logic:

Average days for payout = Number of Enabled Nodes / 288 blocks per day (average).

Number of Enabled nodes can be obtained from `znode count all`.

**Comment by riordant** [comment]
Updated `avgBlockTime` to return general average blocktime over the "n block estimate" currently in place. This is sufficient for what we are using it for and is an efficiency improvement. https://github.com/zcoinofficial/zcoin/commit/91f60cfdffcedaf39d733067aab9af674318379b
