### ISSUE TITLE
zcoind using 25% CPU even when blockchain and znode list are synced

### ISSUE THREAD

**Issue by justanwar** [zcoinofficial/zcoin-client#89]
## Desired behaviour

zcoind idles with a low CPU usage. 

## Actual behaviour

zcoind uses up to 25% of CPU (one core) even when blockchain and znode list are synced. Debug log does not indicate anything out of the ordinary.

## Steps to reproduce

Run zcoin-client on Windows 10 1809.

![image](https://user-images.githubusercontent.com/42809091/66459291-53549180-eaa7-11e9-81ee-49334a16bca3.png)

**Comment by justanwar** [comment]
![image](https://user-images.githubusercontent.com/42809091/66470203-b8b27d80-eabb-11e9-9631-298ba8a8c9b0.png)

**Comment by reubenyap** [comment]
On my Ryzen 2700X it consumes about 8%. Looks to be quite heavy on one core.

**Comment by riordant** [comment]
Pushing this to the 1.0.0 release.

**Comment by a-bezrukov** [comment]
The root cause of the issue is the way we process network messages (from other nodes and Znodes). This is exactly this code, ran in a separate thread, produces such CPU load: https://github.com/zcoinofficial/zcoin/blob/b8411b8a67fe04e34355758716c257b2d8324621/src/net.cpp#L1991
In core14 this mechanism will be changed and the issue will very likely disappear. Can it wait for core14?

**Comment by justanwar** [comment]
I have no problems with waiting for core14.

After everything synced in Zcoin-QT on Windows, the CPU usage is very low (3-5%) which is expected as it is mostly idling and even when it receive network messages, the spikes are temporary.

This is in stark contrast with the GUI client + zcoind, where it uses one core of the CPU all the time.

Is there a difference between how zcoind versus zcoin-qt operates?

**Comment by qashban4** [comment]
@a-bezrukov Andrey couldn't find root cause and reproduce the same. We may have to retest after GUI 1.0 release and check the same. If not reproduced, we may have to debug on the PCs that we find the issue on.

**Comment by riordant** [comment]
Resolved following Docker builds.
