### ISSUE TITLE
Private Mint shows the same TXID for every mint output

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#94]
For example, in the following image I have one mint transaction of 78 XZC, with 6 mint outputs - 3x25 and 3x1. 
<img width="449" alt="Screenshot 2019-10-14 at 19 08 04" src="https://user-images.githubusercontent.com/6988731/66750174-f8aba300-eeb5-11e9-9a70-cf8701381cfe.png">
To only show the same txid once, or show output information for each mint, eg. 
```
vout - 0
mint - 25
```
etc.

**Comment by justanwar** [comment]
![image](https://user-images.githubusercontent.com/42809091/66760637-1b997f80-eed5-11e9-87c4-c0286536bfd2.png)
Additionally the tooltip and the Detail column shows the wrong number of confirmations (Current block number plus 1)
