### ISSUE TITLE
General Znode Data changes

### ISSUE THREAD

**Issue by justanwar** [zcoinofficial/zcoin-client#95]
![image](https://user-images.githubusercontent.com/42809091/66832650-ec464980-ef8c-11e9-9ad6-75813a9ec321.png)

Adding `Enabled Znodes` count will help us while we wait for deterministic masternodes since currently users can end up with a wrong Znode list without knowing and looking at the Enabled count is one way to determine it. This is the case with the current QT wallet and zcoind.

I believe the enabled count is already present, just need to display it.

Also see #87

**Comment by riordant** [comment]
@sproxet this is Anwar's comment there:
```
For "Average Days for Payout", we can go with this logic:

Average days for payout = Number of Enabled Nodes / 288 blocks per day (average).

Number of Enabled nodes can be obtained from znode count all.
```

So as zcoind already sends the total, and the 288 is constant, the final calculation can be done on the client end.

**Comment by riordant** [comment]
`countEnabled` flag added to `apiStatus` in https://github.com/zcoinofficial/zcoin/commit/34682b6543c45a8eb4be15c100c4c3563e37aae2. @sproxet please update client
